config:
    twitter:
        oauth_access_token: 94845449-AI5ONQM3KIxRVHTuRL7hsyDTIkGcAMdm9VRxLB2h2
        oauth_access_token_secret: wXEXoC2uSULKBHs5RLuHZ4T5UbACsdlOF4mnzsvY9TmYJ
        consumer_key: q12jfzLQpiuoLy6XwWpJUtsJA
        consumer_secret: hEuOqDzQ0DkoQdZ5I4Q5GYFTCNCwTAVJlCi53lFdv2GaIvf7qk
